# Codecov Configuration
# Documentation: https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto
        if_ci_failed: error

      backend:
        target: 85%
        threshold: 0.5%
        paths:
          - "backend/src/"
        flags:
          - backend

      frontend:
        target: 70%
        threshold: 0.5%
        paths:
          - "frontend/src/"
        flags:
          - frontend

    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  backend:
    paths:
      - backend/src/
    carryforward: false

  frontend:
    paths:
      - frontend/src/
    carryforward: false

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/mockData/**"
  - "**/*.config.*"
  - "**/*.d.ts"
  - "frontend/e2e/**"
  - "backend/tests/**"
  - "docs/**"

# Require passing CI before updating coverage
codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
