// <auto-generated />
using System;
using Chickquita.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chickquita.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207091546_AddFlockDataIntegrityConstraints")]
    partial class AddFlockDataIntegrityConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chickquita.Domain.Entities.Coop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_coops_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_coops_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_coops_tenant_id");

                    b.ToTable("coops", (string)null);
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.Flock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoopId")
                        .HasColumnType("uuid")
                        .HasColumnName("coop_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentChicks")
                        .HasColumnType("integer")
                        .HasColumnName("current_chicks");

                    b.Property<int>("CurrentHens")
                        .HasColumnType("integer")
                        .HasColumnName("current_hens");

                    b.Property<int>("CurrentRoosters")
                        .HasColumnType("integer")
                        .HasColumnName("current_roosters");

                    b.Property<DateTime>("HatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hatch_date");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoopId")
                        .HasDatabaseName("ix_flocks_coop_id");

                    b.HasIndex("HatchDate")
                        .HasDatabaseName("ix_flocks_hatch_date");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_flocks_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_flocks_tenant_id");

                    b.HasIndex("CoopId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_flocks_coop_id_identifier");

                    b.ToTable("flocks", (string)null);
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.FlockHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_date");

                    b.Property<int>("Chicks")
                        .HasColumnType("integer")
                        .HasColumnName("chicks");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("flock_id");

                    b.Property<int>("Hens")
                        .HasColumnType("integer")
                        .HasColumnName("hens");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.Property<int>("Roosters")
                        .HasColumnType("integer")
                        .HasColumnName("roosters");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChangeDate")
                        .HasDatabaseName("ix_flock_history_change_date");

                    b.HasIndex("FlockId")
                        .HasDatabaseName("ix_flock_history_flock_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_flock_history_tenant_id");

                    b.ToTable("flock_history", (string)null);
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("clerk_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_clerk_user_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_tenants_email");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.Coop", b =>
                {
                    b.HasOne("Chickquita.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.Flock", b =>
                {
                    b.HasOne("Chickquita.Domain.Entities.Coop", "Coop")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coop");
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.FlockHistory", b =>
                {
                    b.HasOne("Chickquita.Domain.Entities.Flock", "Flock")
                        .WithMany("History")
                        .HasForeignKey("FlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flock");
                });

            modelBuilder.Entity("Chickquita.Domain.Entities.Flock", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
